"""GridAgent-Bench v2 — multi-tie, PF-validated restoration reconfiguration search.  [GOAL_v2 M5]

v1 defect: ``_restore_config`` scored exactly ONE tie (``best_seq = [t]``) and called
``pp.runpp`` only to test *convergence*. Consequence: the "optimal" restoration was always a single
switch, so the myopic ``greedy`` baseline was identical to the oracle and the benchmark could not
discriminate between any two policies.

v2 searches the real reconfiguration space. After the faulted section is isolated, the de-energized
region may consist of several islands; each island can be back-fed from a different neighbouring
feeder, and a single big tie may be *thermally infeasible* while two smaller ties are feasible —
that is where multi-switch restoration comes from, and it is generated by physics (AC power flow),
never asserted.

Search structure (exact, not heuristic, within the declared monotone action
budget). A plan is an ORDERED sequence drawn from two operator actions:

  CLOSE an initially open tie at most once. Every resulting state must satisfy
  radiality, fault non-energization, and ``pf_feasible`` (thermal plus EN 50160
  voltage). A safe closure is retained even when it initially restores no load:
  it may connect two dark islands before a later back-feed.

  OPEN an initially closed sectionalizer at most once while both endpoints are
  truly de-energized. This is the load-transfer / split-restoration action. It
  may permit faster staged restoration even when a single slower tie would
  eventually restore the whole island.

The production proof engine is state dynamic programming. Different action
orders that reach the same physical switch state have identical future
transitions and elapsed switching time, so only the ordering with the smallest
accumulated restoration timing is retained. Weighted and unweighted objectives
are tracked separately. The result is marked proven only when every reachable
state through ``max_depth`` is exhausted without hitting ``max_nodes``.

Cost of a leaf is the shared ``cost_model.restoration_cost`` — the same function every arm is
scored with (M1), so the oracle's cost is a real cost and ``regret(oracle) == 0`` by construction.
"""
from __future__ import annotations

import copy
from dataclasses import dataclass, field
from itertools import combinations, permutations

import networkx as nx

from gridagent.agent_interface.cost_model import (
    DEFAULT_HORIZON_MIN, restoration_cost, switch_time_min,
)
from gridagent.simulation.grid_bank import (
    _switch_bus_pair, collapsed_graph, energized_buses, n_independent_loops, unsupplied,
)
from gridagent.simulation.pf_feasibility import pf_feasible

BRUTE_FORCE_MAX_POOL = 8      # feeders whose action pool is <= this get the independent brute force
DEFAULT_MAX_DEPTH = 4         # at most this many switching operations in a restoration plan
DEFAULT_MAX_OPENS = 2         # at most this many sectionalizing OPENs (split / shed) per plan
DEFAULT_MAX_NODES = 3000      # DFS safety cap; exceeding it downgrades proven_optimal


# --------------------------------------------------------------------------- #
# leaf record
# --------------------------------------------------------------------------- #
@dataclass
class Leaf:
    ops: tuple                      # ordered ({'switch_id','closed'}, ...) operations
    events: tuple                   # ((n_customers, op_index), ...) unweighted
    w_events: tuple                 # ((weighted_customers, op_index), ...)
    restored_buses: frozenset
    restored_customers: int
    restored_weighted: float
    n_closes: int = 0               # tie closures (an OPEN is a sectionalizing/shedding action)


@dataclass
class ReconfigResult:
    faulted_buses: tuple
    de_energized_buses: frozenset
    down_customers: int
    # --- optimum (weighted objective) ---
    switch_sequence: list
    restore_events: list
    restored_buses: frozenset
    restored_customers: int
    restored_weighted: float
    cost_kwh: float
    n_switch_ops: int
    n_tie_closures: int
    n_sectionalizing_opens: int
    # --- anchors / diagnostics ---
    cost_noop_kwh: float
    controllable_customers: int          # max restorable over ALL feasible plans
    controllable_weighted: float
    controllable_buses: frozenset        # deterministic max-weight restoration state
    greedy_switch_sequence: list         # best SINGLE-tie plan
    greedy_cost_kwh: float
    greedy_restored_customers: int
    greedy_suboptimality: float          # greedy_regret - oracle_regret (>= 0)
    backfeed_conflict: bool              # a higher-restoring tie exists but is PF-infeasible
    priority_divergence: bool            # weighted optimum != unweighted optimum
    initial_pf_feasible: bool            # post-fault state is safe before policy actions
    initial_pf_metrics: dict
    proven_optimal: bool
    method: str
    n_leaves: int
    n_pf_calls: int
    pf_infeasible_ties: list
    notes: list = field(default_factory=list)


# --------------------------------------------------------------------------- #
# net preparation
# --------------------------------------------------------------------------- #
def isolate_fault(net, faulted_buses, *, load_scale: float = 1.0):
    """Deep copy of ``net`` with the load trajectory applied and the faulted section isolated.

    Isolation opens every line incident to a faulted bus (the sectionalizers on both sides have
    operated) and takes the faulted buses' own loads out of service — they cannot be restored by
    reconfiguration, only by repair.
    """
    n = copy.deepcopy(net)
    if load_scale != 1.0:
        for col in ("p_mw", "q_mvar"):
            if col in n.load.columns:
                n.load[col] = n.load[col] * float(load_scale)
        if len(n.sgen) and "p_mw" in n.sgen.columns:
            n.sgen["p_mw"] = n.sgen["p_mw"] * float(load_scale)
    fb = {int(b) for b in faulted_buses if b is not None and int(b) >= 0}
    for li in list(n.line.index):
        if int(n.line.at[li, "from_bus"]) in fb or int(n.line.at[li, "to_bus"]) in fb:
            n.line.at[li, "in_service"] = False
    for ld in list(n.load.index):
        if int(n.load.at[ld, "bus"]) in fb:
            n.load.at[ld, "in_service"] = False
    return n


def open_tie_ids(net, sw_meta: dict | None = None) -> list[int]:
    """Normally-open switches usable for back-feed (restricted to manifest 'tie' type if given)."""
    opn = [int(s) for s in net.switch.index[~net.switch.closed]]
    if sw_meta:
        ties = {int(s) for s, m in sw_meta.items() if m.get("type") == "tie"}
        if ties:
            opn = [s for s in opn if s in ties]
    return sorted(opn)


SECTIONALIZING_TYPES = ("sectionalizer", "RMU/LBS")


def sectionalizer_ids(net, sw_meta: dict | None = None) -> list[int]:
    """Normally-CLOSED field switching devices the operator may open to split/shed a dead island.
    Breakers are excluded: they are protection, not sectionalizing."""
    cl = [int(s) for s in net.switch.index[net.switch.closed]]
    if sw_meta:
        sec = {int(s) for s, m in sw_meta.items() if m.get("type") in SECTIONALIZING_TYPES}
        cl = [s for s in cl if s in sec]
    return sorted(cl)


def _cust_of(buses, cust: dict) -> int:
    return int(sum(int(cust.get(int(b), 0)) for b in buses))


def graph_state(net, ext_sources: set) -> tuple:
    """(collapsed graph, energized set, n_independent_loops) from ONE graph build.

    ``energized_buses`` and ``n_independent_loops`` each rebuild the collapsed graph, and the DFS
    calls both at every node — folding them into one build is a ~3x speedup with identical
    semantics (energized == reachable from an ext_grid bus, the definition
    ``pandapower.topology.unsupplied_buses`` implements).
    """
    g = collapsed_graph(net)
    reach = set()
    for s in ext_sources:
        if s in g and s not in reach:
            reach |= nx.node_connected_component(g, s)
    return g, {int(b) for b in reach}, len(nx.cycle_basis(g))


def _wcust_of(buses, cust: dict, weights: dict | None) -> float:
    if not weights:
        return float(_cust_of(buses, cust))
    return float(sum(int(cust.get(int(b), 0)) * float(weights.get(int(b), 1.0)) for b in buses))


# --------------------------------------------------------------------------- #
# the search
# --------------------------------------------------------------------------- #
def _solve_reconfiguration_legacy(net, faulted_buses, cust: dict,
                                  sw_meta: dict | None = None, *,
                                  weights: dict | None = None,
                                  horizon_min: float = DEFAULT_HORIZON_MIN,
                                  max_depth: int = DEFAULT_MAX_DEPTH,
                                  load_scale: float = 1.0,
                                  max_nodes: int = DEFAULT_MAX_NODES,
                                  max_opens: int = DEFAULT_MAX_OPENS,
                                  ties: list | None = None) -> ReconfigResult:
    """Retired invalid DFS retained only to reproduce pre-correction artifacts.

    New code must call ``solve_reconfiguration`` below. This implementation's
    split-restoration shortcut produced false proof flags and is intentionally
    private.
    """
    sw_meta = sw_meta or {}
    fb = tuple(sorted(int(b) for b in faulted_buses if b is not None and int(b) >= 0))
    base = isolate_fault(net, fb, load_scale=load_scale)
    all_ties = list(ties) if ties is not None else open_tie_ids(base, sw_meta)
    all_secs = sectionalizer_ids(base, sw_meta) if max_opens > 0 else []

    dead0 = unsupplied(base) - set(fb)
    down_customers = _cust_of(dead0, cust)

    # --- static switch->bus-pair map (endpoints never change; only 'closed' does) ---
    pair_of: dict[int, tuple] = {}
    for sid in list(all_ties) + list(all_secs):
        p = _switch_bus_pair(base, int(sid))
        if p is not None:
            pair_of[int(sid)] = (int(p[0]), int(p[1]))

    # A sectionalizing OPEN is only ever useful if it CUTS a dead island — i.e. its two endpoints
    # are still connected to each other through the dead region, so opening it separates load from
    # the point a tie would back-feed. Switches that are not cut edges (parallel bus couplers, or
    # already-severed pairs) can never change what is restorable, so they are not in the action
    # space. This is a correctness-preserving reduction, not a heuristic.
    sec_in_dead = [s for s in all_secs
                   if s in pair_of and pair_of[s][0] in dead0 and pair_of[s][1] in dead0]

    ext_sources = {int(b) for b in base.ext_grid.bus}
    sec_candidates: list[int] = []

    leaves: list[Leaf] = []
    initial_pf_feasible, initial_pf_metrics = pf_feasible(base)
    pf_calls = 1
    nodes = 0
    truncated = False
    pf_infeasible = set()
    _pf_cache: dict = {}

    def _pf_ok(key) -> bool:
        nonlocal pf_calls
        if key in _pf_cache:
            return _pf_cache[key]
        pf_calls += 1
        ok, _m = pf_feasible(base)
        _pf_cache[key] = ok
        return ok

    # `base` is mutated in place and reverted on backtrack — deep-copying a pandapower net per DFS
    # node dominated the runtime and is unnecessary: the only mutated column is switch.closed.
    def dfs(energized, touched, ops, events, w_events, restored, n_opens, last_open, allow_opens):
        nonlocal nodes, truncated
        # record this state as a leaf (the empty plan is the no-op leaf, scored separately)
        if ops:
            leaves.append(Leaf(tuple(ops), tuple(events), tuple(w_events), frozenset(restored),
                               _cust_of(restored, cust), _wcust_of(restored, cust, weights),
                               sum(1 for o in ops if o["closed"])))
        if len(ops) >= max_depth or truncated:
            return

        # ---- action 1: CLOSE a usable tie (back-feed a dead island) ----
        for sid in all_ties:
            if sid in touched or sid not in pair_of:
                continue
            a, b = pair_of[sid]
            if (a in energized) == (b in energized):
                continue                       # both live -> mesh; both dead -> no source
            nodes += 1
            if nodes > max_nodes:
                truncated = True
                return
            base.switch.at[sid, "closed"] = True
            try:
                _g, new_en, loops = graph_state(base, ext_sources)
                if loops != 0:
                    continue
                if set(fb) & new_en:
                    continue
                gained = new_en - energized
                if not gained:
                    continue                   # restored nobody -> never optimal
                if not _pf_ok(frozenset(touched | {sid})):
                    pf_infeasible.add(int(sid))
                    continue
                k = len(ops)
                dfs(new_en, touched | {sid},
                    ops + [{"switch_id": int(sid), "closed": True}],
                    events + [(_cust_of(gained, cust), k)],
                    w_events + [(_wcust_of(gained, cust, weights), k)],
                    restored | gained, n_opens, None, allow_opens)
            finally:
                base.switch.at[sid, "closed"] = False
            if truncated:
                return

        # ---- action 2: OPEN a sectionalizer inside the dead region (split / shed) ----
        if not allow_opens or n_opens >= max_opens:
            return
        for sid in sec_candidates:
            if sid in touched:
                continue
            if last_open is not None and sid <= last_open:
                continue                       # canonical order for consecutive opens
            a, b = pair_of[sid]
            if a in energized or b in energized:
                continue                       # never drop already-restored / healthy load
            nodes += 1
            if nodes > max_nodes:
                truncated = True
                return
            base.switch.at[sid, "closed"] = False
            try:
                # the open must actually CUT the dead island (otherwise nothing it enables differs)
                g = collapsed_graph(base)
                if a in g and b in g and nx.has_path(g, a, b):
                    continue
                dfs(energized, touched | {sid},
                    ops + [{"switch_id": int(sid), "closed": False}],
                    events, w_events, restored, n_opens + 1, int(sid), allow_opens)
            finally:
                base.switch.at[sid, "closed"] = True
            if truncated:
                return

    _g0, en0, _l0 = graph_state(base, ext_sources)

    # PASS 1 — tie closures only. Cheap, and when no connectivity-valid close is rejected by AC-PF
    # it is also COMPLETE: a sectionalizing OPEN never enlarges the restorable set, it only sheds
    # load, so when capacity never binds an open is strictly dominated by not opening.
    dfs(en0, set(), [], [], [], set(), 0, None, False)

    # If some pass-1 plan already restores EVERY de-energized customer, no plan can restore more and
    # an OPEN can only add switching time — pass 1 is then globally optimal and pass 2 is skipped.
    all_restored_p1 = any(l.restored_customers >= down_customers for l in leaves) and down_customers > 0

    shed_search_used = False
    if pf_infeasible and max_opens > 0 and sec_in_dead and not all_restored_p1:
        # PASS 2 — capacity DID bind: re-search with split/shed enabled, but only over the dead
        # islands where a tie was actually rejected by AC-PF. Shedding load in an island whose tie
        # is already feasible cannot help (it only removes load and adds switching time), so those
        # sectionalizers are outside the useful action space.
        g0 = collapsed_graph(base)
        blocked_islands: set = set()
        for t in pf_infeasible:
            for endp in pair_of.get(int(t), ()):
                if endp in dead0 and endp in g0:
                    blocked_islands |= nx.node_connected_component(g0, endp)
        sec_candidates = [s for s in sec_in_dead
                          if pair_of[s][0] in blocked_islands and pair_of[s][1] in blocked_islands]
        if sec_candidates:
            shed_search_used = True
            leaves.clear()
            nodes = 0
            pf_infeasible_pass1 = set(pf_infeasible)
            dfs(en0, set(), [], [], [], set(), 0, None, True)
            pf_infeasible |= pf_infeasible_pass1

    # ---- anchors: the controllable set is the max restorable over ALL feasible plans ---- #
    controllable = max((l.restored_customers for l in leaves), default=0)
    controllable_w = max((l.restored_weighted for l in leaves), default=0.0)
    anchor_leaf = min(
        leaves,
        key=lambda leaf: (
            -round(float(leaf.restored_weighted), 9),
            -int(leaf.restored_customers),
            tuple(sorted(int(bus) for bus in leaf.restored_buses)),
            len(leaf.ops),
            tuple(
                (int(operation["switch_id"]), bool(operation["closed"]))
                for operation in leaf.ops
            ),
        ),
        default=Leaf((), (), (), frozenset(), 0, 0.0, 0),
    )
    cost_noop = restoration_cost(0, controllable_w, [], sw_meta, horizon_min)

    def _cost(leaf: Leaf, weighted: bool) -> float:
        ev = leaf.w_events if weighted else leaf.events
        tot = leaf.restored_weighted if weighted else leaf.restored_customers
        ctrl = controllable_w if weighted else controllable
        return restoration_cost(list(ev), max(ctrl - tot, 0.0), list(leaf.ops), sw_meta, horizon_min)

    noop_leaf = Leaf((), (), (), frozenset(), 0, 0.0, 0)
    _key = lambda x: (round(x[1], 9), len(x[0].ops), tuple(sorted(o["switch_id"] for o in x[0].ops)))
    scored = [(l, _cost(l, True)) for l in leaves] + [(noop_leaf, cost_noop)]
    best, best_cost = min(scored, key=_key)

    # unweighted optimum (does critical-load priority change the answer? -> D4 axis)
    scored_u = [(l, _cost(l, False)) for l in leaves] + [(noop_leaf, restoration_cost(
        0, controllable, [], sw_meta, horizon_min))]
    best_u, _ = min(scored_u, key=_key)
    priority_divergence = bool(tuple(map(str, best.ops)) != tuple(map(str, best_u.ops)))

    # greedy = the best SINGLE tie-closure plan (no sectionalizing) under the SAME cost model —
    # this is exactly what the myopic incumbent can do, so oracle-vs-greedy measures the value of
    # multi-step planning, not of a different metric.
    singles = [(l, c) for l, c in scored if len(l.ops) == 1 and l.ops[0]["closed"]]
    if singles:
        g_leaf, g_cost = min(singles, key=_key)
    else:
        g_leaf, g_cost = noop_leaf, cost_noop

    denom = max(cost_noop - best_cost, 1e-9)
    greedy_subopt = float(min(max((g_cost - best_cost) / denom, 0.0), 1.0))

    # a back-feed conflict = at least one connectivity-valid tie closure is rejected by AC-PF
    # (capacity, not connectivity, is what forces the multi-step plan)
    backfeed_conflict = bool(pf_infeasible)

    proven = (not truncated)
    method = "exhaustive-dfs" if proven else "bounded-dfs(best-known)"

    return ReconfigResult(
        faulted_buses=fb,
        de_energized_buses=frozenset(int(b) for b in dead0),
        down_customers=down_customers,
        switch_sequence=[dict(o) for o in best.ops],
        restore_events=[(int(n), int(k)) for n, k in best.events],
        restored_buses=best.restored_buses,
        restored_customers=int(best.restored_customers),
        restored_weighted=float(best.restored_weighted),
        cost_kwh=float(best_cost),
        n_switch_ops=len(best.ops),
        n_tie_closures=int(best.n_closes),
        n_sectionalizing_opens=int(len(best.ops) - best.n_closes),
        cost_noop_kwh=float(cost_noop),
        controllable_customers=int(controllable),
        controllable_weighted=float(controllable_w),
        controllable_buses=frozenset(anchor_leaf.restored_buses),
        greedy_switch_sequence=[dict(o) for o in g_leaf.ops],
        greedy_cost_kwh=float(g_cost),
        greedy_restored_customers=int(g_leaf.restored_customers),
        greedy_suboptimality=greedy_subopt,
        backfeed_conflict=backfeed_conflict,
        priority_divergence=priority_divergence,
        initial_pf_feasible=bool(initial_pf_feasible),
        initial_pf_metrics=dict(initial_pf_metrics),
        proven_optimal=bool(proven),
        method=method,
        n_leaves=len(leaves),
        n_pf_calls=pf_calls,
        pf_infeasible_ties=sorted(pf_infeasible),
        notes=(["dfs_node_cap_hit"] if truncated else [])
              + (["shed_search"] if shed_search_used else []),
    )


# --------------------------------------------------------------------------- #
# controller-space state-DP search
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class _DPPath:
    ops: tuple
    events: tuple
    w_events: tuple
    timing_customers_min: float
    timing_weighted_min: float


@dataclass(frozen=True)
class _DPPhysical:
    valid: bool
    energized: frozenset
    restored: frozenset
    reason: str


def solve_reconfiguration(net, faulted_buses, cust: dict,
                          sw_meta: dict | None = None, *,
                          weights: dict | None = None,
                          horizon_min: float = DEFAULT_HORIZON_MIN,
                          max_depth: int = DEFAULT_MAX_DEPTH,
                          load_scale: float = 1.0,
                          max_nodes: int = DEFAULT_MAX_NODES,
                          max_opens: int = DEFAULT_MAX_OPENS,
                          ties: list | None = None) -> ReconfigResult:
    """Exact state-DP optimum in the declared monotone controller action class.

    A state is the set of ties closed and true-dark sectionalizers opened.
    Different action orders reaching the same physical state have identical
    future transitions and elapsed switching time, so only the ordering with
    the smallest accumulated restoration timing is retained.  Weighted and
    unweighted objectives are tracked separately.

    Unlike the retired DFS, this search:

    * always considers split restoration, even when one tie eventually
      restores every interrupted customer;
    * considers a safe tie closure that initially restores no load, because it
      can connect dark islands before a later back-feed; and
    * marks ``proven_optimal`` only after exhausting every reachable state up
      to ``max_depth`` without hitting ``max_nodes``.
    """
    sw_meta = sw_meta or {}
    fb = tuple(sorted(
        int(bus) for bus in faulted_buses
        if bus is not None and int(bus) >= 0
    ))
    faulted = set(fb)
    base = isolate_fault(net, fb, load_scale=load_scale)
    all_ties = (
        sorted(int(switch_id) for switch_id in ties)
        if ties is not None
        else open_tie_ids(base, sw_meta)
    )
    all_secs = sectionalizer_ids(base, sw_meta) if max_opens > 0 else []

    dead0 = {int(bus) for bus in unsupplied(base)} - faulted
    down_customers = _cust_of(dead0, cust)
    ext_sources = {int(bus) for bus in base.ext_grid.bus}

    pair_of = {}
    for switch_id in all_ties + all_secs:
        pair = _switch_bus_pair(base, int(switch_id))
        if pair is not None:
            pair_of[int(switch_id)] = (int(pair[0]), int(pair[1]))
    all_ties = [
        int(switch_id) for switch_id in all_ties
        if int(switch_id) in pair_of
    ]
    # A monotone oracle never opens an energized device.  Every potentially
    # useful split therefore starts inside the initial true-dark region.
    all_secs = [
        int(switch_id) for switch_id in all_secs
        if int(switch_id) in pair_of
        and pair_of[int(switch_id)][0] in dead0
        and pair_of[int(switch_id)][1] in dead0
    ]
    controlled = all_ties + all_secs
    initial_closed = {
        int(switch_id): bool(base.switch.at[int(switch_id), "closed"])
        for switch_id in controlled
    }

    initial_pf_feasible, initial_pf_metrics = pf_feasible(base)
    pf_calls = 1
    nodes = 0
    truncated = False
    pf_infeasible = set()
    physical_cache = {}
    pf_cache = {(
        frozenset(), frozenset()
    ): bool(initial_pf_feasible)}

    def _set_state(key):
        closed_ties, open_secs = key
        for switch_id, closed in initial_closed.items():
            base.switch.at[switch_id, "closed"] = closed
        for switch_id in closed_ties:
            base.switch.at[switch_id, "closed"] = True
        for switch_id in open_secs:
            base.switch.at[switch_id, "closed"] = False

    def _evaluate(key) -> _DPPhysical:
        nonlocal pf_calls
        cached = physical_cache.get(key)
        if cached is not None:
            return cached
        _set_state(key)
        _graph, energized, loops = graph_state(base, ext_sources)
        if loops:
            result = _DPPhysical(False, frozenset(), frozenset(), "radiality")
        elif faulted & energized:
            result = _DPPhysical(
                False, frozenset(), frozenset(), "fault_energized"
            )
        else:
            ok = pf_cache.get(key)
            if ok is None:
                pf_calls += 1
                ok = bool(pf_feasible(base)[0])
                pf_cache[key] = ok
            if not ok:
                result = _DPPhysical(
                    False, frozenset(), frozenset(), "power_flow"
                )
            else:
                energized = frozenset(int(bus) for bus in energized)
                result = _DPPhysical(
                    True,
                    energized,
                    frozenset(dead0 & set(energized)),
                    "valid",
                )
        physical_cache[key] = result
        return result

    def _elapsed(path: _DPPath) -> float:
        return float(sum(
            switch_time_min(op["switch_id"], sw_meta) for op in path.ops
        ))

    def _advance(path: _DPPath, switch_id: int, closed: bool,
                 gained: set, op_index: int) -> _DPPath:
        operation = {"switch_id": int(switch_id), "closed": bool(closed)}
        completion = _elapsed(path) + switch_time_min(switch_id, sw_meta)
        gained_customers = _cust_of(gained, cust)
        gained_weighted = _wcust_of(gained, cust, weights)
        return _DPPath(
            ops=path.ops + (operation,),
            events=path.events + (
                ((gained_customers, op_index),) if gained_customers > 0 else ()
            ),
            w_events=path.w_events + (
                ((gained_weighted, op_index),) if gained_weighted > 0 else ()
            ),
            timing_customers_min=(
                path.timing_customers_min
                + gained_customers * min(completion, horizon_min)
            ),
            timing_weighted_min=(
                path.timing_weighted_min
                + gained_weighted * min(completion, horizon_min)
            ),
        )

    def _ops_key(path: _DPPath) -> tuple:
        return tuple(
            (int(op["switch_id"]), bool(op["closed"])) for op in path.ops
        )

    def _better(candidate: _DPPath, incumbent: _DPPath | None,
                *, weighted: bool) -> bool:
        if incumbent is None:
            return True
        candidate_value = (
            candidate.timing_weighted_min
            if weighted else candidate.timing_customers_min
        )
        incumbent_value = (
            incumbent.timing_weighted_min
            if weighted else incumbent.timing_customers_min
        )
        return (
            candidate_value < incumbent_value - 1e-9
            or (
                abs(candidate_value - incumbent_value) <= 1e-9
                and _ops_key(candidate) < _ops_key(incumbent)
            )
        )

    empty_key = (frozenset(), frozenset())
    empty_path = _DPPath((), (), (), 0.0, 0.0)
    layer_keys = {empty_key}
    layer_weighted = {empty_key: empty_path}
    layer_unweighted = {empty_key: empty_path}
    all_weighted = dict(layer_weighted)
    all_unweighted = dict(layer_unweighted)

    for depth in range(max(int(max_depth), 0)):
        next_keys = set()
        next_weighted = {}
        next_unweighted = {}
        for key in sorted(
            layer_keys,
            key=lambda value: (tuple(sorted(value[0])), tuple(sorted(value[1]))),
        ):
            current = _evaluate(key)
            if not current.valid:
                continue
            closed_ties, open_secs = key

            for switch_id in all_ties:
                if switch_id in closed_ties:
                    continue
                nodes += 1
                if nodes > max_nodes:
                    truncated = True
                    break
                candidate_key = (
                    frozenset(set(closed_ties) | {switch_id}),
                    open_secs,
                )
                candidate_state = _evaluate(candidate_key)
                if not candidate_state.valid:
                    if candidate_state.reason == "power_flow":
                        pf_infeasible.add(int(switch_id))
                    continue
                gained = set(candidate_state.energized - current.energized)
                next_keys.add(candidate_key)
                for source, target, weighted_mode in (
                    (layer_weighted, next_weighted, True),
                    (layer_unweighted, next_unweighted, False),
                ):
                    candidate_path = _advance(
                        source[key], switch_id, True, gained, depth
                    )
                    if _better(
                        candidate_path,
                        target.get(candidate_key),
                        weighted=weighted_mode,
                    ):
                        target[candidate_key] = candidate_path
            if truncated:
                break

            if len(open_secs) >= max_opens:
                continue
            for switch_id in all_secs:
                if switch_id in open_secs:
                    continue
                endpoint_a, endpoint_b = pair_of[switch_id]
                if (
                    endpoint_a in current.energized
                    or endpoint_b in current.energized
                ):
                    continue
                nodes += 1
                if nodes > max_nodes:
                    truncated = True
                    break
                candidate_key = (
                    closed_ties,
                    frozenset(set(open_secs) | {switch_id}),
                )
                _set_state(candidate_key)
                graph = collapsed_graph(base)
                if (
                    endpoint_a in graph
                    and endpoint_b in graph
                    and nx.has_path(graph, endpoint_a, endpoint_b)
                ):
                    continue
                candidate_state = _evaluate(candidate_key)
                if not candidate_state.valid:
                    continue
                gained = set(candidate_state.energized - current.energized)
                next_keys.add(candidate_key)
                for source, target, weighted_mode in (
                    (layer_weighted, next_weighted, True),
                    (layer_unweighted, next_unweighted, False),
                ):
                    candidate_path = _advance(
                        source[key], switch_id, False, gained, depth
                    )
                    if _better(
                        candidate_path,
                        target.get(candidate_key),
                        weighted=weighted_mode,
                    ):
                        target[candidate_key] = candidate_path
            if truncated:
                break

        all_weighted.update(next_weighted)
        all_unweighted.update(next_unweighted)
        layer_keys = next_keys
        layer_weighted = next_weighted
        layer_unweighted = next_unweighted
        if truncated or not layer_keys:
            break

    controllable = max(
        (
            _cust_of(_evaluate(key).restored, cust)
            for key in all_weighted
        ),
        default=0,
    )
    controllable_w = max(
        (
            _wcust_of(_evaluate(key).restored, cust, weights)
            for key in all_weighted
        ),
        default=0.0,
    )
    # ``controllable_weighted`` is a scalar maximum and the cost-optimal plan
    # need not attain it.  Retain the physical state that does attain the
    # maximum so downstream counterfactual scoring can use the same customer
    # anchor.  The remaining terms make the choice deterministic when several
    # states have equal nominal weighted restoration.
    controllable_key = min(
        all_weighted,
        key=lambda key: (
            -round(
                float(_wcust_of(_evaluate(key).restored, cust, weights)),
                9,
            ),
            -int(_cust_of(_evaluate(key).restored, cust)),
            tuple(sorted(int(bus) for bus in _evaluate(key).restored)),
            tuple(sorted(int(switch_id) for switch_id in key[0])),
            tuple(sorted(int(switch_id) for switch_id in key[1])),
        ),
    )
    controllable_buses = frozenset(_evaluate(controllable_key).restored)
    cost_noop = restoration_cost(
        0, controllable_w, [], sw_meta, horizon_min
    )

    def _path_cost(key, path: _DPPath, *, weighted: bool) -> float:
        restored = _evaluate(key).restored
        if weighted:
            total = _wcust_of(restored, cust, weights)
            return restoration_cost(
                list(path.w_events),
                max(controllable_w - total, 0.0),
                list(path.ops),
                sw_meta,
                horizon_min,
            )
        total = _cust_of(restored, cust)
        return restoration_cost(
            list(path.events),
            max(controllable - total, 0.0),
            list(path.ops),
            sw_meta,
            horizon_min,
        )

    def _best(paths, *, weighted: bool):
        candidates = []
        for key, path in paths.items():
            cost = _path_cost(key, path, weighted=weighted)
            candidates.append((
                round(cost, 9),
                len(path.ops),
                _ops_key(path),
                key,
                path,
                cost,
            ))
        return min(candidates)

    _rounded, _length, _signature, best_key, best, best_cost = _best(
        all_weighted, weighted=True
    )
    _ur, _ul, _us, best_u_key, best_u, _best_u_cost = _best(
        all_unweighted, weighted=False
    )
    best_state = _evaluate(best_key)
    priority_divergence = _ops_key(best) != _ops_key(best_u)

    singles = []
    for key, path in all_weighted.items():
        if len(path.ops) == 1 and bool(path.ops[0]["closed"]):
            cost = _path_cost(key, path, weighted=True)
            singles.append((
                round(cost, 9), len(path.ops), _ops_key(path), key, path, cost
            ))
    if singles:
        _gr, _gl, _gs, _gk, greedy, greedy_cost = min(singles)
        greedy_state = _evaluate(_gk)
    else:
        greedy = empty_path
        greedy_cost = cost_noop
        greedy_state = _evaluate(empty_key)

    denominator = max(cost_noop - best_cost, 1e-9)
    greedy_suboptimality = float(min(max(
        (greedy_cost - best_cost) / denominator, 0.0
    ), 1.0))
    proven = not truncated
    method = (
        "exhaustive-controller-state-dp"
        if proven else "bounded-controller-state-dp(best-known)"
    )
    restored_buses = best_state.restored
    restored_customers = _cust_of(restored_buses, cust)
    restored_weighted = _wcust_of(restored_buses, cust, weights)

    return ReconfigResult(
        faulted_buses=fb,
        de_energized_buses=frozenset(dead0),
        down_customers=down_customers,
        switch_sequence=[dict(operation) for operation in best.ops],
        restore_events=[
            (int(count), int(index)) for count, index in best.events
        ],
        restored_buses=frozenset(restored_buses),
        restored_customers=int(restored_customers),
        restored_weighted=float(restored_weighted),
        cost_kwh=float(best_cost),
        n_switch_ops=len(best.ops),
        n_tie_closures=sum(
            1 for operation in best.ops if operation["closed"]
        ),
        n_sectionalizing_opens=sum(
            1 for operation in best.ops if not operation["closed"]
        ),
        cost_noop_kwh=float(cost_noop),
        controllable_customers=int(controllable),
        controllable_weighted=float(controllable_w),
        controllable_buses=controllable_buses,
        greedy_switch_sequence=[
            dict(operation) for operation in greedy.ops
        ],
        greedy_cost_kwh=float(greedy_cost),
        greedy_restored_customers=int(
            _cust_of(greedy_state.restored, cust)
        ),
        greedy_suboptimality=greedy_suboptimality,
        backfeed_conflict=bool(pf_infeasible),
        priority_divergence=bool(priority_divergence),
        initial_pf_feasible=bool(initial_pf_feasible),
        initial_pf_metrics=dict(initial_pf_metrics),
        proven_optimal=bool(proven),
        method=method,
        n_leaves=max(len(all_weighted) - 1, 0),
        n_pf_calls=int(pf_calls),
        pf_infeasible_ties=sorted(pf_infeasible),
        notes=(
            ["state_dp_node_cap_hit"] if truncated else []
        ) + [
            "proof_scope_monotone_true_dark_depth_"
            f"{int(max_depth)}_max_opens_{int(max_opens)}",
            "zero_gain_tie_closures_included",
            "all_true_dark_sectionalizers_included",
        ],
    )


# --------------------------------------------------------------------------- #
# independent brute-force cross-check (CIGRE-scale)
# --------------------------------------------------------------------------- #
def brute_force_optimum(net, faulted_buses, cust: dict, sw_meta: dict | None = None, *,
                        weights: dict | None = None, horizon_min: float = DEFAULT_HORIZON_MIN,
                        load_scale: float = 1.0, max_depth: int = DEFAULT_MAX_DEPTH,
                        max_pool: int = BRUTE_FORCE_MAX_POOL) -> dict:
    """INDEPENDENT optimum on CIGRE-scale: enumerate EVERY ordered action sequence of length
    <= max_depth over the FULL action pool (close any open tie / open any closed sectionalizing
    device) and replay each one from scratch.

    Deliberately written without any of ``solve_reconfiguration``'s structural pruning — no
    "exactly one live endpoint" precondition, no "never open a live switch" rule, no canonical
    ordering of opens, no incremental state reuse. If the DFS's pruning rules were wrong, this
    enumeration would find a cheaper plan and the agreement check would fail. That is the point.

    Returns {"feasible", "cost_kwh", "switch_sequence", "n_evaluated"} or {"skipped": reason}.
    """
    sw_meta = sw_meta or {}
    fb = tuple(sorted(int(b) for b in faulted_buses if b is not None and int(b) >= 0))
    base = isolate_fault(net, fb, load_scale=load_scale)
    pool = ([{"switch_id": s, "closed": True} for s in open_tie_ids(base, sw_meta)]
            + [{"switch_id": s, "closed": False} for s in sectionalizer_ids(base, sw_meta)])
    if len(pool) > max_pool:
        return {"skipped": f"action pool {len(pool)} > brute-force limit {max_pool}"}

    plans, n_eval = [], 0
    for r in range(0, max_depth + 1):
        for order in permutations(range(len(pool)), r):
            n_eval += 1
            cur = copy.deepcopy(base)
            energized = energized_buses(cur)
            ok_plan, events, restored, ops = True, [], set(), []
            for k, pi in enumerate(order):
                act = pool[pi]
                cur.switch.at[act["switch_id"], "closed"] = act["closed"]
                if n_independent_loops(cur) != 0:
                    ok_plan = False
                    break
                new_en = energized_buses(cur)
                if set(fb) & new_en:
                    ok_plan = False
                    break
                if not pf_feasible(cur)[0]:
                    ok_plan = False
                    break
                gained = new_en - energized
                lost = energized - new_en
                if lost & restored:            # dropping load already restored: allowed, but the
                    ok_plan = False            # cost model does not represent re-interruption
                    break
                if gained:
                    events.append((_wcust_of(gained, cust, weights), k))
                restored |= gained
                energized = new_en
                ops.append(act)
            if ok_plan:
                plans.append((tuple(map(str, ops)), tuple(events), frozenset(restored), list(ops)))

    controllable_w = max((_wcust_of(r, cust, weights) for _s, _e, r, _o in plans), default=0.0)
    best_cost, best_ops = None, []
    for _sig, events, restored, ops in plans:
        tot = _wcust_of(restored, cust, weights)
        c = restoration_cost(list(events), max(controllable_w - tot, 0.0), list(ops),
                             sw_meta, horizon_min)
        if best_cost is None or c < best_cost - 1e-9:
            best_cost, best_ops = c, list(ops)
    return {"feasible": best_cost is not None, "cost_kwh": float(best_cost or 0.0),
            "switch_sequence": [dict(o) for o in best_ops], "n_evaluated": n_eval,
            "controllable_weighted": float(controllable_w)}
